#GET http://localhost:5000/api/movies/
#GET http://localhost:5000/api/movies/4

# GET http://localhost:5000/api/users/
# GET http://localhost:5000/api/users/5

# GET http://localhost:5000/api/wishlist/
